import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Initialize i18n
i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        title: 'Ramaini (Marriage) Registration Form',
        subtitle: 'Jai Purnabrahma Kabir Saheb',
        personalInfo: 'Personal Information',
        girlName: "Girl's Name",
        girlFatherName: "Father's Name",
        girlMotherName: "Mother's Name",
        girlDOB: 'Date of Birth',
        girlAge: 'Age',
        contactInfo: 'Contact Information',
        fullAddress: 'Full Address',
        tehsil: 'Tehsil',
        district: 'District',
        state: 'State',
        mobileNumber: 'Mobile Number',
        religiousInfo: 'Religious Information',
        firstNameReceiptDate: 'First Name Receipt Date',
        satnamReceiptDate: 'Satnam Receipt Date',
        nameReceiptDate: 'Name Receipt Date',
        abstractReceiptDate: 'Abstract Receipt Date',
        declaration: 'Declaration',
        declarantInfo:
          'I am {{name}}, {{relation}} of {{resident}}, wanting {{person}} from {{state}} to marry.',
        marriageDetails: 'Marriage Details',
        childName: "Child's Name",
        childFrom: 'Child From',
        childDistrict: 'Child District',
        ramainiSiriNo: 'Ramaini Siri No.',
        location: 'Location',
        dateOfRamaini: 'Date of Ramaini',
        questions: 'Important Questions',
        isAdult:
          'Has the girl attained the age of 18 years as per government rules?',
        isDowryFree: 'Is this a dowry-free marriage?',
        agreeWithRules: 'Do you agree with the rules of Ramaini marriage?',
        isAlreadyMarried: 'Is the girl already married?',
        note: 'Note: Aadhaar card of boy and girl and parents, photocopy of Namdiksha form, 10th mark sheet and photos are mandatory.',
        signatureSection: 'Signatures',
        familySignature: 'Family Signature',
        girlSignature: "Girl's Signature",
        sigName: 'Name',
        sigMobile: 'Mobile',
        sigRelation: 'Relationship with girl',
        date: 'Date',
        submit: 'Submit Registration',
        requiredField: 'This field is required',
        invalidMobile: 'Invalid mobile number',
        invalidAge: 'Age must be 18 or above',
        yes: 'Yes',
        no: 'No',
        uploadPhoto: 'Upload Photo',
        uploadSignature: 'Upload Signature',
        success: 'Form submitted successfully!',
        error: 'Error submitting form. Please try again.',
        toggleLanguage: 'भाषा बदलें / Change Language',
        acceptDeclaration: 'I accept and agree to the declaration',
      },
    },
    hi: {
      translation: {
        title: 'रमैनी (विवाह) पंजीकरण प्रपत्र',
        subtitle: 'जय पूर्णब्रह्म कबीर साहेब',
        personalInfo: 'व्यक्तिगत जानकारी',
        girlName: 'लड़की का नाम',
        girlFatherName: 'पिता का नाम',
        girlMotherName: 'माता का नाम',
        girlDOB: 'जन्म तिथि',
        girlAge: 'आयु',
        contactInfo: 'संपर्क जानकारी',
        fullAddress: 'पूरा पता',
        tehsil: 'तहसील',
        district: 'जिला',
        state: 'राज्य',
        mobileNumber: 'मोबाइल नंबर',
        religiousInfo: 'धार्मिक जानकारी',
        firstNameReceiptDate: 'प्रथम नाम प्राप्ति तिथि',
        satnamReceiptDate: 'सतनाम प्राप्ति तिथि',
        nameReceiptDate: 'नाम प्राप्ति की तिथि',
        abstractReceiptDate: 'सार प्राप्ति तिथि',
        declaration: 'घोषणा',
        declarantInfo:
          'मैं {{name}}, {{resident}} का {{relation}}, {{state}} से {{person}} से विवाह करना चाहता हूं।',
        marriageDetails: 'विवाह विवरण',
        childName: 'बच्चे का नाम',
        childFrom: 'बच्चा कहां से',
        childDistrict: 'बच्चे का जिला',
        ramainiSiriNo: 'रमैनी सिरी नंबर',
        location: 'स्थान',
        dateOfRamaini: 'रमैनी की तिथि',
        questions: 'महत्वपूर्ण प्रश्न',
        isAdult:
          'क्या लड़की सरकारी नियमों के अनुसार 18 वर्ष की आयु प्राप्त कर चुकी है?',
        isDowryFree: 'क्या यह दहेज-मुक्त विवाह है?',
        agreeWithRules: 'क्या आप रमैनी विवाह के नियमों से सहमत हैं?',
        isAlreadyMarried: 'क्या लड़की पहले से विवाहित है?',
        note: 'नोट: लड़के और लड़की और माता-पिता का आधार कार्ड, नामदीक्षा फॉर्म की फोटोकॉपी, 10वीं की मार्कशीट और फोटो अनिवार्य हैं।',
        signatureSection: 'हस्ताक्षर',
        familySignature: 'परिवार का हस्ताक्षर',
        girlSignature: 'लड़की का हस्ताक्षर',
        sigName: 'नाम',
        sigMobile: 'मोबाइल',
        sigRelation: 'लड़की के साथ संबंध',
        date: 'तिथि',
        submit: 'पंजीकरण जमा करें',
        requiredField: 'यह फ़ील्ड आवश्यक है',
        invalidMobile: 'अमान्य मोबाइल नंबर',
        invalidAge: 'आयु 18 या उससे अधिक होनी चाहिए',
        yes: 'हां',
        no: 'नहीं',
        uploadPhoto: 'फोटो अपलोड करें',
        uploadSignature: 'हस्ताक्षर अपलोड करें',
        success: 'फॉर्म सफलतापूर्वक जमा किया गया!',
        error: 'फॉर्म जमा करने में त्रुटि। कृपया पुनः प्रयास करें।',
        toggleLanguage: 'Change Language / भाषा बदलें',
        acceptDeclaration: 'मैं घोषणा को स्वीकार करता हूं',
      },
    },
  },
  lng: 'en',
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
