import mongoose from 'mongoose';

const BoyFormSchema = new mongoose.Schema({
  boyName: { type: String, required: true },
  boyFatherName: { type: String, required: true },
  boyMotherName: { type: String, required: true },
  boyDOB: { type: String, required: true },
  boyAge: { type: String, required: true },
  fullAddress: { type: String, required: true },
  tehsil: { type: String, required: true },
  district: { type: String, required: true },
  state: { type: String, required: true },
  mobileNumber: { type: String, required: true },
  firstNameReceiptDate: { type: String, required: true },
  satnamReceiptDate: { type: String, required: true },
  dateOfNameReceipt: { type: String, required: true },
  abstractReceiptDate: { type: String, required: true },
  declarantName: { type: String, required: true },
  declarantSon: { type: String, required: true },
  declarantResident: { type: String, required: true },
  wantToMarry: { type: String, required: true },
  wantToMarryState: { type: String, required: true },
  childName: { type: String, required: true },
  childFrom: { type: String, required: true },
  childDistrict: { type: String, required: true },
  ramainSiriNo: { type: String, required: true },
  location: { type: String, required: true },
  dateOfRamaini: { type: String, required: true },
  isAdult: { type: String, default: 'No' },
  isDowryFree: { type: String, default: 'No' },
  agreeWithRules: { type: String, default: 'No' },
  isAlreadyMarried: { type: String, default: 'No' },
  boySignatureName: { type: String, required: true },
  boySignatureMobile: { type: String, required: true },
  boySignatureRelation: { type: String, required: true },
  boySignatureDate: { type: String, required: true },

  boyPhoto: { type: String },
  girlPhoto: { type: String },
  boySignature: { type: String },
  familySignature: { type: String },
}, {
  timestamps: true,
});

export default mongoose.model('BoyForm', BoyFormSchema);
